version: '2'
services:
  products_php:
    container_name: products_php_apache
    image: products:latest
    build:
      dockerfile: php/Dockerfile
    user: '1000:1000'
    volumes:
      - ../products:/var/www/html/:rw
      - ./apache_conf:/etc/apache2/sites-enabled/
    ports:
      - '80:80'
    networks:
      - products_network
    depends_on:
      - products_mysql
  products_composer:
    image: composer/composer:2.5.4
  products_mysql:
    container_name: products_mysql
    image: mysql:5.7.40
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wagnyjagare
      MYSQL_DATABASE: checker
      MYSQL_USER: products
      MYSQL_PASSWORD: qwerty
      ALLOW_EMPTY_PASSWORD: no
    volumes:
      - products_mysql_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/my.cnf
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - products_network

  phpmyadmin:
    container_name: products_pma
    image: phpmyadmin:5.2.1
    ports:
      - '8080:80'
    environment:
      PMA_HOST: products_mysql
    depends_on:
      - products_mysql
    networks:
      - products_network

volumes:
  products_mysql_data:
networks:
  products_network:
    driver: bridge
