version: '2'
services:
  php:
    container_name: products_php_apache
    build:
      dockerfile: php/Dockerfile
    user: '1000:1000'  
    volumes:
      - ../products:/var/www/html/:rw
      - ./apache_conf:/etc/apache2/sites-enabled/
    ports:
      - '80:80'
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    container_name: products_mysql
    image: mysql:5.7.40
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wagnyjagare
      MYSQL_DATABASE: checker
      MYSQL_USER: products
      MYSQL_PASSWORD: qwerty
      ALLOW_EMPTY_PASSWORD: no
    volumes:
      - products_mysql_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/my.cnf
    networks:
      - my-network

  phpmyadmin:
    container_name: products_pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - my-network

volumes:
  products_mysql_data:
networks:
  my-network:
    driver: bridge
